# Generated by Django 4.1.1 on 2022-09-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes4all', '0003_notes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='summary_link',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default='sample class', max_length=250),
        ),
    ]
